import random
import re
from collections import deque


# creates a generator that yields the elements of the input list in a random order infinitely without repeating except
# when the list runs out
def choice_no_repeats(in_list):
    source = deque()
    while True:
        if len(source) == 0:
            source.extend(random.sample(in_list, len(in_list)))
        yield source.pop()


with open("poetry.txt", encoding="utf-8") as poetry_file:
    raw_poems = poetry_file.read().split("\n---\n")
    poetry = [p.strip() for p in raw_poems if p.strip()]

poetry_generator = choice_no_repeats(poetry)

nicknames = [
    "Accidental Genius", "Ace", "Adorable", "Alpha", "Amazing", "Angel Eyes", "Angel Face",
    "Angel Heart", "Angelito", "Atom", "Autumn", "Azúcar", "Baba Ganoush", "Bad Kitty", "Bam Bam",
    "Bambi", "Beagle", "Bean", "Beanie", "Bear", "Bearded Genius", "Biggie", "Biscuit", "Bitsy",
    "Blister", "Blondie", "Blue Eyes", "Blueberry", "Book Worm", "Boss", "Bowie", "Bowler",
    "Brainiac", "Brave Heart", "Breadmaker", "Bright Eyes", "Bro", "Brown Eyes", "Buckeye",
    "Buckshot", "Buddy", "Bugger", "Buster", "Butcher", "Button", "Cabbie", "Cadillac", "Cakes",
    "Candy", "Captain", "Captain Peroxide", "Caramel", "Care Bear", "Caretaker", "Champ",
    "Chardonnay", "Charming", "Chef", "Chicago Blackout", "Chocolate Thunder", "Chubs", "Chuckles",
    "Cinnamon", "Claws", "Coco", "Commando", "Confessor", "Cookie", "Cool Whip", "Cosmo",
    "Crash Override", "Crash Test", "Crazy Eights", "Cream", "Cuddle Bear", "Cuddle Buddy",
    "Cuddle Bug", "Cuddle Bunny", "Cuddle Muffin", "Cuddly Bear", "Cuddly Wuddly", "Cupcakes",
    "Curls", "Cute Bunny", "Cute Pie", "Cuteness", "Cutesy Pie", "Cutie", "Cutie Boo", "Cutie Head",
    "Cutie Pants", "Cutie Patootie", "Cutie Pie", "Daddy", "Dancing Madman", "Dark Horse",
    "Darling", "Dashing", "Dear", "Dear Heart", "Dearest", "Dearest One", "Dearie", "Deep Water",
    "Destiny", "Dew Drop", "Diamond", "Dimples", "Dolce", "Dove", "Dragonfly", "Dream Boat",
    "Dream Guy", "Dream Lover", "Dreamer", "Dreamweaver", "Dreamy", "Duckling", "Eclipse",
    "Egghead", "Electric Player", "Elf", "Enigma", "Everything", "Eye Candy", "Fantasy",
    "Favorite", "Feisty", "Fine Wine", "Firecracker", "Firefly", "Flakes", "Flame", "Flash",
    "Flint", "Fluffy", "Foxy", "Freak", "Freckles", "Frostbite", "Frozen Fire", "Fruit Cake",
    "Fruit Loop", "Fun Size", "Gangsta", "Gas Man", "Gem", "Genie", "Genius", "Ghost", "Giggles",
    "Gold", "Good Looking", "Goody Goody", "Goof", "Goof Ball", "Goofy", "Google", "Gorgeous",
    "Grasshopper", "Grave Digger", "Green", "Grimm", "Guillotine", "Gumdrop", "Gummy Bear",
    "Gunhawk", "Happiness", "Happy Face", "Haven", "Heart & Soul", "Heart Stopper", "Heart Throb",
    "Heart’s Desire", "Heartbreaker", "Heartie", "Heaven Sent", "Hero", "Hightower", "Hobbit",
    "Hog Butcher", "Hollywood", "Honey", "Honey Bagel", "Honey Bear", "Honey Bee", "Honey Bird",
    "Honey Bun", "Honey Bunch", "Honey Bunny", "Honey Lips", "Honey Love", "Honey Muffin",
    "Honey Pie", "Honey Pot", "Honey Sugar Bumps", "Honeysuckle", "Hop", "Hot Cakes",
    "Hot Chocolate", "Hot Lips", "Hot Pants", "Hot Stuff", "Hotness", "Hotshot", "Hotsy-Totsy",
    "Hottie", "Hottie Tottie", "Houston", "Hubba Bubba", "Huggie", "Huggies", "Huggy Bear",
    "Hugster", "Hun", "Hyper", "Ivy", "Jazzy", "Jester", "Jewel", "Jigsaw", "Jockey",
    "Joker’s Grin", "Joy", "Judge", "K-9", "Keystone", "Khal", "Kickstart", "Kiddo", "Kill Switch",
    "Kingfisher", "Kissy Face", "Kit Kat", "Kitchen", "Kitten", "Kitty Cat", "Knockout", "Knuckles",
    "Lady Killer", "Lamb", "Lamb Chop", "Lambkin", "Lambkins", "Lapooheart", "Legs", "Lemon",
    "Life Mate", "Lifeline", "Light Priest", "Lightning Ball", "Lil Dove", "Lil One",
    "Lil’ Heart Breaker", "Liquid Science", "Little Bear", "Little Bit", "Little Bits",
    "Little Cobra", "Little Dove", "Little General", "Little Guy", "Little Lamb", "Little Puff",
    "Lollipop", "Looker", "Lord Nikon", "Lovatar", "Love", "Love Bear", "Love Boodle", "Love Bug",
    "Love Face", "Love Genie", "Love Lumps", "Love Muffin", "Love Nugget", "Lovebird", "Lover Boy",
    "Lover Doll", "Lucky", "Lucky Charm", "Luna", "Lunar", "Mad Jack", "Magic", "Magic Guy",
    "Magician", "Major", "Manimal", "Marbles", "Married Man", "Marshmallow", "Mellow", "Melody",
    "Mental", "Micro", "Mine", "Mini", "Mini Me", "Minion", "Minnie Mouse", "Misty Eyes",
    "Mon Amour", "Mon Coeur", "Monkey", "Mookie", "Mooky Porky", "Moon Beam", "Moonlight",
    "Moonshine", "Motherboard", "Mouse", "Movie Star", "Fabulous", "Gadget", "Lucky", "Peppermint",
    "Spy", "Thanksgiving", "Wholesome", "Muffin", "Munchies", "Munchkin", "Nacho", "Natural Mess",
    "Nibbles", "Night Train", "Nightmare King", "Nine", "Ninja", "Nugget", "Num Nums", "Nutty",
    "Odd Duck", "Omega", "One and Only", "Onion King", "Oreo", "Other Half", "Overrun", "Pancake",
    "Panda", "Panda Bear", "Papa Smurf", "Paradise", "Paramour", "Passion", "Passion Fruit",
    "Peach", "Peaches", "Peaches and Crème", "Peachy", "Peachy Pie", "Peanut", "Pearl", "Pebbles",
    "Perfect", "Pet", "Pickle", "Pickle Pie", "Pikachu", "Pineapple", "Pineapple Chunk",
    "Pint Size", "Pipsqueak", "Pluto", "Poker Face", "Pop Tart", "Precious", "Prince", "Prize",
    "Prometheus", "Psycho Thinker", "Pudding", "Pumpkin", "Pumpkin Pie", "Punk", "Puppy", "Pusher",
    "Quake", "Quirky", "Rabbit", "Radical", "Raindrop", "Rashes", "Ray", "Rebel", "Red",
    "Ride or Die", "Roadblock", "Rockstar", "Rooster", "Rug-Rat", "Rum-Rum", "Runner", "Saint",
    "Sandbox", "Santa Baby", "Scooter", "Scrapper", "Screwtape", "Scrumptious", "Serial Killer",
    "Sex Bomb", "Sex Kitten", "Sex Muffin", "Sexiness", "Sexual Chocolate", "Sexy", "Sexy Angel",
    "Sexy Bear", "Sexy Devil", "Sexy Dork", "Sexy Eyes", "Sexy Guy", "Sexy Pants", "Sexy Pie",
    "Shadow", "Shadow Chaser", "Share Bear", "Sherwood Gladiator", "Shining Star", "Shooter",
    "Short Stuff", "Shortcake", "Shorty", "Shot Glass", "Shrimpy", "Shug", "Shy",
    "Sidewalk Enforcer", "Silly Goose", "Skippy", "Skittles", "Skull Crusher", "Sky", "Sky Bully",
    "Slick", "Slicky", "Slow Trot", "Small Fry", "Smallie", "Smart Cookie", "Smarty", "Smiles",
    "Smiley", "Smiley Face", "Snake Eyes", "Snappy", "Snicker Doodle", "Snookums", "Snow Bunny",
    "Snow Hound", "Snow Pea", "Snowflake", "Snuggle Able", "Snuggle Bear", "Snuggles", "Snuka Bear",
    "Soda Pop", "Sofa King", "Soldier", "Soul Friend", "Soul Mate", "Spark", "Sparky", "Speedwell",
    "Sphinx", "Spiky", "Spirit", "Sport", "Spring", "Springheel Jack", "Sprinkles", "Squatch",
    "Squirrel", "Squishy", "Stacker of Wheat", "Star", "Star Bright", "Star Light", "Stepper",
    "Sugams", "Sugar", "Sugar Babe", "Sugar Bear", "Sugar Biscuit", "Sugar Boy", "Sugar Lips",
    "Sugar Man", "Sugar Pants", "Suicide Jockey", "Suitor", "Sunflower", "Sunshine", "Super Guy",
    "Super Man", "Super Star", "Swampmasher", "Sweet", "Sweet Baby", "Sweet Dream", "Sweet Heart",
    "Sweet Kitten", "Sweet Lips", "Sweet Love", "Sweet Lover", "Sweet One", "Sweet Tart",
    "Sweet Thang", "Sweetie", "Swerve", "Tacklebox", "Take Away", "Tarzan", "Tater Tot", "Tea Cup",
    "Teddy", "Teddy Bear", "Tender Heart", "Tesoro", "The China Wall", "Thrasher", "Tiger", "Tiggy",
    "Tiny Boo", "Toe", "Toolmaker", "Tough Guy", "Tough Nut", "Treasure", "Treasure Trove",
    "Tricky", "Trip", "True Love", "TumTums", "Turtle", "Turtle Dove", "Tweetie", "Tweetie-Pie",
    "Tweetums", "Twinkie", "Twinkle Toes", "Twitch", "Uber", "Ultimate", "Unicorn", "Unstoppable",
    "Untamed", "Vagabond Warrior", "Valentine", "Viking", "Vita", "Voluntary", "Vortex", "Waffles",
    "Washer", "Waylay Dave", "Wee-One", "Westie", "Wheels", "Wolfie", "Wonder Guy", "Wonder Man",
    "Wonderful", "Woo Bear", "Woo Woo", "Woody", "Wookie", "Wookums", "Wordsmith", "Wuggle Bear",
    "Wuggles", "Xoxo", "Yankee", "Young Guy", "Youngest", "Yummers", "Yummy", "Yummy Bear", "Zany",
    "Zesty Dragon", "Zod", "Abba Zabba", "Almond Joy", "Amorcita", "Angel", "Angel Baby",
    "Angel Face", "Angel Legs", "Angel Wing", "Angelita", "Aphrodite", "Babe", "Baby", "Baby Bear",
    "Baby Carrot", "Baby Doll", "Baby Girl", "Baby Love", "Baby Spice", "Babycakes", "Bambi",
    "Barbie", "Bean", "Bear", "Beautiful", "Beauty", "Bella", "Betty Boo", "Big Love", "Bite-size",
    "Bitty Love", "Blondie", "Blueberry Pie", "Bonita", "Boo", "Booboo", "Bookworm", "Booty Beauty",
    "Bossy", "Brownie", "Bubba", "Bubble Butt", "Bubble Gum", "Bubbles", "Buddy", "Bug", "Bugaboo",
    "Bugaloo", "Buggly Boo", "Bundt Cake", "Butter Butt", "Butter Tart", "Butterbomb", "Butterbutt",
    "Buttercup", "Butterfinger", "Butterfly", "Butterscotch", "Button", "Candy Cane", "Carmel",
    "Carmelita", "Carmella", "Cat woman", "Cheezit", "Cherubie", "Chicken Tender", "Chicken Wing",
    "Chiquitita", "Chubby Cheeks", "Chubs", "Cinderella", "Cinnabon", "Cinnamon", "Cookie",
    "Corn Nut", "Cowgirl", "Cracker Jack", "Crispie Treat", "Critter", "Cuddle Bug", "Cuddly Boop",
    "Cuddly Duddly", "Cupcake", "Curls", "Curly-Q", "Curvy", "Cute Boot", "Cute Bot", "Cuteness",
    "Cutie", "Cutie Bug", "Cutie Buggles", "Cutie Cuddles", "Cutie Patootie", "Cutie Pie",
    "Cutie Sniggles", "Cutie Snuggles", "Cutie Toes", "Cutie Wiggles", "Daisy", "Damsel", "Darling",
    "Dear", "Dearest", "Dibbles", "Dilly Dolly", "Dimples", "Doll face", "Dolly", "Dorito",
    "Double Bubble", "Double Love", "Double Stuff", "Double Trouble", "Dove", "Dovey Lovey",
    "Dream Girl", "Duchess", "Dum Dum", "Dumpling", "Ella", "Enchantress", "Fibbles",
    "Fillity Tuna", "Filly Billy", "Flame", "Foxy Lady", "French Fry", "Frito", "Funfetti",
    "Funion", "Fun-size", "Gaga", "Gibbles", "Giggles", "Glass of Sunshine", "Goal Baby", "Goddess",
    "Goldie", "Goldie Locks", "Goo Goo", "Goober", "Goody Bar", "Gorgeous", "Green Love",
    "Gribbles", "Gubble Bum", "Gumball", "Gumdrop", "Gummy Bear", "Gummy Worm", "Half Pint",
    "Heaven-Sent", "Hershey’s", "Honey", "Honey Buns", "Honey Butt", "Honey Loaf", "Honey Tots",
    "Honey Wiggles", "Honeymaid", "Honeypot", "Hot Bod", "Hot Butt", "Hot Cakes", "Hot Cross Buns",
    "Hot French Fry", "Hot Mama", "Hot Potato", "Hot Sauce", "Hot Tater Tot", "Hot Thing",
    "Hotlips", "Hottie Po-tottie", "Hurricane", "Icee Pop", "Ittle Skittle",
    "Itty Bitty Sugar Bomb", "Jammer", "Jazzie", "Jellie Belly", "Jelly Bean", "Jelly Belly",
    "Jelly Sweets", "Jellybean", "Jolly Rancher", "Juicy", "Juicy Fruity", "Juliet", "Junior Mint",
    "Khaki Lassie", "Kiddo", "Kit Kat", "Kitten", "Kitty", "Lady Bug", "Lady Godiva", "Laffy Taffy",
    "Lervey Dervy", "Libbles", "Lifesaver", "Lil Antoinette", "Lil Ma’am", "Lil Mama", "Lil Miss",
    "Lioness", "Lip Smacker", "Little Bear", "Little Love", "Little Mama", "Little Rascal", "Loca",
    "Lolita", "Lolli Lolli", "Lollipop", "Love", "Love Bud", "Love Muffin", "Love on Fire",
    "Lovebug", "Lover Girl", "Lovey", "Lovey Butt", "Lovey Dovey", "Lovey Tickles", "Luvski",
    "Luvvy Wuvvy", "M&M", "Mallow Cup", "Mama of Drama", "Mamacita", "Mami", "Maple Leaf",
    "Marshymallow", "Meow", "Mi Novia-citita", "Milk Dud", "Milly", "Mine", "Minnie", "Missy",
    "Misty May", "Momacita", "Monkey", "Monkey Toes", "Mooncake", "Mouse", "Muffin", "Muffin Butt",
    "Munchkin", "My Darling", "My Love", "My Lovely", "My Sunshine", "Names Inspired by Angels",
    "Nibbles", "Nutter Butter", "Okie", "Pancake", "Peaches", "Peach-o", "Peanut", "Pearly",
    "Pearls", "Pebbles", "Perf Perf", "Perky", "Pet", "Pickle", "Pink Starburst", "Pinky", "Pippy",
    "Pocket-size", "Pookie", "Pop Tart", "Precious", "Pretty", "Pretty Lady", "Pretty Love",
    "Princesa", "Princess", "Princess Peach", "Principessa", "Principessa", "Pudding", "Pumpkin",
    "Pumpkin Pie", "Punk", "Punkin", "Pussycat", "Quarter Note", "Queenie", "Raisenette",
    "Rapunzel", "Red-Hot Bon Bon", "Rocket Pop", "Rolo", "Rose", "Ruffle", "Runt", "Saddle",
    "Sassy Lassy", "Scarlet", "Secret Sauce", "Señorita", "Sex Enchantress", "Sex Witch",
    "Sexy Lady", "Sexy Mama", "She’s fun, isn’t she?", "Shortcake", "Shorty", "Sirena",
    "Sizzle Pop", "Skittle", "Skittles", "Sleeping Beauty", "Small Fry", "Smartie", "Smarty Pants",
    "Smiles", "Snack", "Snackems", "Snibbles", "Snickerdoodle", "Snickers", "Snizzle Snacks",
    "Snookie", "Snookums", "Snow White", "Snowflake", "Snuggle Bug", "Snuggle Wumps", "Snugglebear",
    "Snuggly Bear", "Splendi", "Sporty Spice", "Sprout", "Squirrel", "Squirt", "Steak Tip",
    "Sticky Bun", "Sugar", "Sugar Babe", "Sugar Bits", "Sugar Bomb", "Sugar Buns", "Sugar Lips",
    "Sugar Mama", "Sugar Mouse", "Sugar Nova", "Sugar Plum", "Sugar Sauce", "Sugar Sugar",
    "Sunshine", "Supergirl", "Sushi", "Sweet Bun", "Sweet Eclair", "Sweet Heart",
    "Sweet Honey Love", "Sweet Loaf", "Sweet Mama", "Sweet Melody", "Sweet Pea", "Sweet Peach",
    "Sweet Tart", "Sweet Thing", "Sweetie", "Sweetie Pie", "Sweets", "Swiss Roll", "Swizzle",
    "Swizzly Sue Thompkins", "Tagalong", "Tart", "Tastee Squeeze", "Tater Tot", "Teddy Graham",
    "Teehee", "Temptress", "Thin Mint", "Thumbelina", "Tibbles", "Tic Tac", "Tiffy Taffy",
    "Tigress", "Tilly", "Tinkerbell", "Tiny One", "Tippy Tappy", "Toffee", "Toffee Lolly", "Tooti",
    "Toots", "Tootsie", "Tootsie Roll", "Tostito", "Triple Love", "Triscuit", "Trolli", "Tuggles",
    "Tutta", "Tutti Frutti", "Tweety", "Twinkie", "Twinkle", "Twix", "Twizzle Top", "Twizzler",
    "Waffles", "Whirly Pop", "Whoopie Pie", "Whopper", "Wifey", "Wittle Wifey", "Wonder Girl",
    "Wonder Woman", "Wuggles", "Yummy"]


def cursive(text, keep_emojis=False):
    emoji_regex = r"(\u00a9|\u00ae|[\u2000-\u3300]|\ud83c[\ud000-\udfff]|\ud83d[\ud000-\udfff]|\ud83e[\ud000-\udfff])"
    cursive_dict = {"0": "𝟢", "1": "𝟣", "2": "𝟤", "3": "𝟥", "4": "𝟦", "5": "𝟧", "6": "𝟨", "7": "𝟩",
                    "8": "𝟪", "9": "𝟫", "a": "𝒶", "b": "𝒷", "c": "𝒸", "d": "𝒹", "e": "𝑒", "f": "𝒻",
                    "g": "𝑔", "h": "𝒽", "i": "𝒾", "j": "𝒿", "k": "𝓀", "l": "𝓁", "m": "𝓂", "n": "𝓃",
                    "o": "𝑜", "p": "𝓅", "q": "𝓆", "r": "𝓇", "s": "𝓈", "t": "𝓉", "u": "𝓊", "v": "𝓋",
                    "w": "𝓌", "x": "𝓍", "y": "𝓎", "z": "𝓏", "A": "𝒜", "B": "𝐵", "C": "𝒞", "D": "𝒟",
                    "E": "𝐸", "F": "𝐹", "G": "𝒢", "H": "𝐻", "I": "𝐼", "J": "𝒥", "K": "𝒦", "L": "𝐿",
                    "M": "𝑀", "N": "𝒩", "O": "𝒪", "P": "𝒫", "Q": "𝒬", "R": "𝑅", "S": "𝒮", "T": "𝒯",
                    "U": "𝒰", "V": "𝒱", "W": "𝒲", "X": "𝒳", "Y": "𝒴", "Z": "𝒵"}
    cursive_text = ''.join([(cursive_dict[x] if x in cursive_dict else x) for x in text.content])
    cleaned_cursive_text = re.sub(emoji_regex, ' ', cursive_text).strip(
    ) if not keep_emojis else cursive_text.strip()
    return cleaned_cursive_text
